version: 2
updates:
  - package-ecosystem: npm
    directory: /
    ignore:
      - dependency-name: "@types/node"
      - dependency-name: "@types/pacote"
      - dependency-name: "@voxpelli/tsconfig"
      - dependency-name: eslint
      - dependency-name: neostandard
      - dependency-name: prettier
      - dependency-name: resolve.exports
      - dependency-name: semver
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
